
default: &default
  adapter: postgresql
  host: localhost
  pool: 5

development:
  <<: *default
  database: apple_critic_development

test:
  <<: *default
  database: apple_critic_test

production:
  <<: *default
  database: apple_critic_production
  username: apple_critic
  password: <%= ENV['APPLE_CRITIC_DATABASE_PASSWORD'] %>
